//Created by Action Script Viewer - https://www.buraks.com/asv
package com.clubpenguin.world
{
    import com.clubpenguin.lib.module.BaseModule;
    import com.clubpenguin.main.model.MainModel;
    import com.clubpenguin.lib.services.AVMBridgeService;

    public class World extends BaseModule 
    {


        override public function init():void
        {
            context = new WorldContext(this, injector);
        }

        override public function destroy():void
        {
            var appModel:MainModel = injector.getInstance(MainModel);
            AVMBridgeService(appModel.getAVMBridge()).close();
            appModel.releaseAVMBridge();
            super.destroy();
        }


    }
}//package com.clubpenguin.world
    //force all classes
    import com.clubpenguin.lib.module.BaseModule; com.clubpenguin.lib.module.BaseModule;
    import com.clubpenguin.world.World; com.clubpenguin.world.World;
    import org.robotlegs.core.IInjector; org.robotlegs.core.IInjector;
    import org.osflash.signals.IDispatcher; org.osflash.signals.IDispatcher;
    import org.osflash.signals.ISignal; org.osflash.signals.ISignal;
    import org.osflash.signals.Signal; org.osflash.signals.Signal;
    import com.clubpenguin.lib.module.IAppSignalBus; com.clubpenguin.lib.module.IAppSignalBus;
    import org.robotlegs.core.IContext; org.robotlegs.core.IContext;
    import org.robotlegs.base.ContextBase; org.robotlegs.base.ContextBase;
    import org.robotlegs.mvcs.Context; org.robotlegs.mvcs.Context;
    import org.robotlegs.core.ISignalContext; org.robotlegs.core.ISignalContext;
    import org.robotlegs.mvcs.SignalContext; org.robotlegs.mvcs.SignalContext;
    import com.clubpenguin.lib.module.BaseModuleContext; com.clubpenguin.lib.module.BaseModuleContext;
    import com.clubpenguin.world.WorldContext; com.clubpenguin.world.WorldContext;
    import org.robotlegs.mvcs.Actor; org.robotlegs.mvcs.Actor;
    import com.clubpenguin.lib.module.IAppModel; com.clubpenguin.lib.module.IAppModel;
    import com.clubpenguin.main.model.MainModel; com.clubpenguin.main.model.MainModel;
    import com.clubpenguin.lib.services.IAVMBridgeService; com.clubpenguin.lib.services.IAVMBridgeService;
    import com.clubpenguin.lib.services.AVMBridgeService; com.clubpenguin.lib.services.AVMBridgeService;
    import org.robotlegs.core.IEventMap; org.robotlegs.core.IEventMap;
    import org.robotlegs.base.EventMap; org.robotlegs.base.EventMap;
    import org.robotlegs.core.IReflector; org.robotlegs.core.IReflector;
    import org.robotlegs.core.ICommandMap; org.robotlegs.core.ICommandMap;
    import org.robotlegs.base.CommandMap; org.robotlegs.base.CommandMap;
    import org.robotlegs.core.IMediatorMap; org.robotlegs.core.IMediatorMap;
    import org.robotlegs.core.IViewMap; org.robotlegs.core.IViewMap;
    import org.robotlegs.base.ViewMapBase; org.robotlegs.base.ViewMapBase;
    import org.robotlegs.base.ViewMap; org.robotlegs.base.ViewMap;
    import org.robotlegs.base.ContextEvent; org.robotlegs.base.ContextEvent;
    import org.robotlegs.base.MediatorMap; org.robotlegs.base.MediatorMap;
    import org.swiftsuspenders.Injector; org.swiftsuspenders.Injector;
    import org.robotlegs.adapters.SwiftSuspendersInjector; org.robotlegs.adapters.SwiftSuspendersInjector;
    import org.swiftsuspenders.Reflector; org.swiftsuspenders.Reflector;
    import org.robotlegs.adapters.SwiftSuspendersReflector; org.robotlegs.adapters.SwiftSuspendersReflector;
    import org.robotlegs.core.ISignalCommandMap; org.robotlegs.core.ISignalCommandMap;
    import org.robotlegs.base.SignalCommandMap; org.robotlegs.base.SignalCommandMap;
    import org.robotlegs.mvcs.Command; org.robotlegs.mvcs.Command;
    import com.clubpenguin.lib.commands.CloseModuleCommand; com.clubpenguin.lib.commands.CloseModuleCommand;
    import com.clubpenguin.lib.signals.CloseModuleSignal; com.clubpenguin.lib.signals.CloseModuleSignal;
    import org.robotlegs.mvcs.SignalCommand; org.robotlegs.mvcs.SignalCommand;
    import com.clubpenguin.world.command.LogAirTowerEventCommand; com.clubpenguin.world.command.LogAirTowerEventCommand;
    import org.robotlegs.core.IMediator; org.robotlegs.core.IMediator;
    import org.robotlegs.base.MediatorBase; org.robotlegs.base.MediatorBase;
    import org.robotlegs.mvcs.Mediator; org.robotlegs.mvcs.Mediator;
    import com.clubpenguin.world.mediator.WorldMediator; com.clubpenguin.world.mediator.WorldMediator;
    import com.clubpenguin.world.signal.AirTowerSignal; com.clubpenguin.world.signal.AirTowerSignal;
    import com.clubpenguin.world.command.startup.InitAVMCommunicationCommand; com.clubpenguin.world.command.startup.InitAVMCommunicationCommand;
    import com.clubpenguin.world.model.WorldModel; com.clubpenguin.world.model.WorldModel;
    import com.clubpenguin.world.command.startup.LoadAS2Command; com.clubpenguin.world.command.startup.LoadAS2Command;
    import com.clubpenguin.world.command.SendBICommand; com.clubpenguin.world.command.SendBICommand;
    import com.clubpenguin.world.command.SendUserSubmissionCommand; com.clubpenguin.world.command.SendUserSubmissionCommand;
    import com.clubpenguin.world.view.AS2ContentView; com.clubpenguin.world.view.AS2ContentView;
    import com.clubpenguin.world.command.startup.SendAVM1FlashVarsCommand; com.clubpenguin.world.command.startup.SendAVM1FlashVarsCommand;
    import com.clubpenguin.lib.vo.IPlayerVO; com.clubpenguin.lib.vo.IPlayerVO;
    import com.clubpenguin.lib.vo.PathsVO; com.clubpenguin.lib.vo.PathsVO;
    import com.clubpenguin.lib.vo.EnvironmentDataVO; com.clubpenguin.lib.vo.EnvironmentDataVO;
    import com.clubpenguin.lib.managers.localization.ILocalizationManager; com.clubpenguin.lib.managers.localization.ILocalizationManager;
    import com.clubpenguin.managers.localization.LocalizationManager; com.clubpenguin.managers.localization.LocalizationManager;
    import com.clubpenguin.lib.util.Log; com.clubpenguin.lib.util.Log;
    import com.clubpenguin.lib.view.BaseEmbeddedAssetView; com.clubpenguin.lib.view.BaseEmbeddedAssetView;
    import com.clubpenguin.main.view.PromptView; com.clubpenguin.main.view.PromptView;
    import com.clubpenguin.lib.managers.resource.IResourceManager; com.clubpenguin.lib.managers.resource.IResourceManager;
    import com.clubpenguin.managers.resource.ResourceManager; com.clubpenguin.managers.resource.ResourceManager;
    import com.clubpenguin.main.model.puffle.PuffleStateManager; com.clubpenguin.main.model.puffle.PuffleStateManager;
    import com.clubpenguin.lib.module.INotificationModule; com.clubpenguin.lib.module.INotificationModule;
    import com.clubpenguin.main.service.ErrorService; com.clubpenguin.main.service.ErrorService;
    import com.clubpenguin.lib.vo.AVMBridgeMessage; com.clubpenguin.lib.vo.AVMBridgeMessage;
    import com.clubpenguin.lib.enums.Enum; com.clubpenguin.lib.enums.Enum;
    import com.clubpenguin.lib.enums.errors.ErrorCodeEnum; com.clubpenguin.lib.enums.errors.ErrorCodeEnum;
    import com.clubpenguin.services.socket.world.WorldService; com.clubpenguin.services.socket.world.WorldService;
    import com.asual.swfaddress.SWFAddress; com.asual.swfaddress.SWFAddress;
    import com.asual.swfaddress.SWFAddressEvent; com.asual.swfaddress.SWFAddressEvent;
    import com.clubpenguin.lib.vo.PlayerVO; com.clubpenguin.lib.vo.PlayerVO;
    import com.clubpenguin.lib.module.WindowModuleContext; com.clubpenguin.lib.module.WindowModuleContext;
    import com.clubpenguin.main.view.MainView; com.clubpenguin.main.view.MainView;
    import com.clubpenguin.main.service.DLearningService; com.clubpenguin.main.service.DLearningService;
    import com.clubpenguin.lib.vo.IVO; com.clubpenguin.lib.vo.IVO;
    import com.clubpenguin.lib.vo.puffle.CareItemVO; com.clubpenguin.lib.vo.puffle.CareItemVO;
    import com.hurlant.crypto.hash.IHash; com.hurlant.crypto.hash.IHash;
    import com.hurlant.crypto.hash.MD5; com.hurlant.crypto.hash.MD5;
    import com.clubpenguin.lib.util.collection.ICollection; com.clubpenguin.lib.util.collection.ICollection;
    import com.clubpenguin.lib.util.collection.Bag; com.clubpenguin.lib.util.collection.Bag;
    import com.clubpenguin.services.socket.puffles.PuffleService; com.clubpenguin.services.socket.puffles.PuffleService;
    import com.hurlant.util.Hex; com.hurlant.util.Hex;
    import com.clubpenguin.main.model.ModuleModel; com.clubpenguin.main.model.ModuleModel;
    import com.clubpenguin.main.signal.SignalBus; com.clubpenguin.main.signal.SignalBus;
    import com.clubpenguin.lib.vo.ModuleVO; com.clubpenguin.lib.vo.ModuleVO;
    import com.clubpenguin.lib.module.ModuleFilenamesEnum; com.clubpenguin.lib.module.ModuleFilenamesEnum;
    import com.playdom.tracker.Tracker; com.playdom.tracker.Tracker;
    import com.clubpenguin.lib.vo.puffle.PuffleVO; com.clubpenguin.lib.vo.puffle.PuffleVO;
    import com.clubpenguin.managers.ILoadableAsset; com.clubpenguin.managers.ILoadableAsset;
    import com.clubpenguin.main.overlays.vo.OverlayVO; com.clubpenguin.main.overlays.vo.OverlayVO;
    import com.clubpenguin.main.overlays.vo.LoadingOverlayVO; com.clubpenguin.main.overlays.vo.LoadingOverlayVO;
    import com.clubpenguin.lib.vo.party.PartyVO; com.clubpenguin.lib.vo.party.PartyVO;
    import com.clubpenguin.lib.services.socket.IConnection; com.clubpenguin.lib.services.socket.IConnection;
    import com.clubpenguin.lib.enums.puffle.CareItemInventoryTypeEnum; com.clubpenguin.lib.enums.puffle.CareItemInventoryTypeEnum;
    import com.clubpenguin.main.signal.loadingScreen.ShowLoadingScreenSignal; com.clubpenguin.main.signal.loadingScreen.ShowLoadingScreenSignal;
    import com.clubpenguin.lib.vo.ErrorVO; com.clubpenguin.lib.vo.ErrorVO;
    import com.clubpenguin.main.vo.ComplexPromptVO; com.clubpenguin.main.vo.ComplexPromptVO;
    import com.clubpenguin.main.signal.loadingScreen.UpdateLoadingScreenSignal; com.clubpenguin.main.signal.loadingScreen.UpdateLoadingScreenSignal;
    import com.gskinner.utils.SWFBridgeAS3; com.gskinner.utils.SWFBridgeAS3;
    import com.clubpenguin.main.signal.loadingScreen.HideLoadingScreenSignal; com.clubpenguin.main.signal.loadingScreen.HideLoadingScreenSignal;
    import com.clubpenguin.lib.services.LocalConnectionResponse; com.clubpenguin.lib.services.LocalConnectionResponse;
    import com.clubpenguin.lib.enums.metrics.MetricsConstant; com.clubpenguin.lib.enums.metrics.MetricsConstant;
    import com.clubpenguin.lib.model.IMetricsModel; com.clubpenguin.lib.model.IMetricsModel;
    import com.clubpenguin.main.vo.PromptVO; com.clubpenguin.main.vo.PromptVO;
    import com.clubpenguin.lib.vo.puffle.PuffleTreasureVO; com.clubpenguin.lib.vo.puffle.PuffleTreasureVO;
    import com.adobe.serialization.json.JSON; com.adobe.serialization.json.JSON;
    import com.clubpenguin.lib.vo.map.MapActionVO; com.clubpenguin.lib.vo.map.MapActionVO;
    import com.clubpenguin.lib.services.AVMBridgeMessageQueue; com.clubpenguin.lib.services.AVMBridgeMessageQueue;
    import com.clubpenguin.main.signal.QuestSettingsSignal; com.clubpenguin.main.signal.QuestSettingsSignal;
    import com.clubpenguin.lib.vo.BuddyVO; com.clubpenguin.lib.vo.BuddyVO;
    import com.clubpenguin.lib.friends.FriendsSignalBus; com.clubpenguin.lib.friends.FriendsSignalBus;
    import com.clubpenguin.main.signal.QuestStatusUpdatedSignal; com.clubpenguin.main.signal.QuestStatusUpdatedSignal;
    import com.clubpenguin.main.vo.AssetPromptVO; com.clubpenguin.main.vo.AssetPromptVO;
    import com.clubpenguin.lib.util.SecurityUtil; com.clubpenguin.lib.util.SecurityUtil;
    import org.robotlegs.base.ContextError; org.robotlegs.base.ContextError;
    import org.swiftsuspenders.injectionpoints.InjectionPoint; org.swiftsuspenders.injectionpoints.InjectionPoint;
    import org.swiftsuspenders.injectionpoints.PropertyInjectionPoint; org.swiftsuspenders.injectionpoints.PropertyInjectionPoint;
    import org.swiftsuspenders.injectionpoints.NoParamsConstructorInjectionPoint; org.swiftsuspenders.injectionpoints.NoParamsConstructorInjectionPoint;
    import org.swiftsuspenders.injectionresults.InjectionResult; org.swiftsuspenders.injectionresults.InjectionResult;
    import org.swiftsuspenders.injectionresults.InjectClassResult; org.swiftsuspenders.injectionresults.InjectClassResult;
    import org.swiftsuspenders.injectionresults.InjectOtherRuleResult; org.swiftsuspenders.injectionresults.InjectOtherRuleResult;
    import org.swiftsuspenders.injectionresults.InjectSingletonResult; org.swiftsuspenders.injectionresults.InjectSingletonResult;
    import org.swiftsuspenders.injectionpoints.PostConstructInjectionPoint; org.swiftsuspenders.injectionpoints.PostConstructInjectionPoint;
// //     import org.swiftsuspenders.getConstructor; org.swiftsuspenders.getConstructor;
    import org.swiftsuspenders.InjectionConfig; org.swiftsuspenders.InjectionConfig;
    import org.swiftsuspenders.InjectorError; org.swiftsuspenders.InjectorError;
    import org.swiftsuspenders.injectionresults.InjectValueResult; org.swiftsuspenders.injectionresults.InjectValueResult;
    import org.swiftsuspenders.injectionpoints.MethodInjectionPoint; org.swiftsuspenders.injectionpoints.MethodInjectionPoint;
    import org.swiftsuspenders.injectionpoints.ConstructorInjectionPoint; org.swiftsuspenders.injectionpoints.ConstructorInjectionPoint;
    import com.clubpenguin.world.vo.AirtowerVO; com.clubpenguin.world.vo.AirtowerVO;
    import com.clubpenguin.lib.services.http.LoadSWFService; com.clubpenguin.lib.services.http.LoadSWFService;
    import com.clubpenguin.world.service.LoadAS2ClubPenguinService; com.clubpenguin.world.service.LoadAS2ClubPenguinService;
    import com.clubpenguin.lib.services.http.LoadSWFResponse; com.clubpenguin.lib.services.http.LoadSWFResponse;
    import com.clubpenguin.lib.vo.BiVO; com.clubpenguin.lib.vo.BiVO;
    import com.clubpenguin.lib.vo.UserSubmissionVO; com.clubpenguin.lib.vo.UserSubmissionVO;
    import com.clubpenguin.lib.module.IAppContext; com.clubpenguin.lib.module.IAppContext;
    import com.clubpenguin.lib.enums.resource.CacheTypeEnum; com.clubpenguin.lib.enums.resource.CacheTypeEnum;
    import com.clubpenguin.tools.localtext.core.ILocalizedText; com.clubpenguin.tools.localtext.core.ILocalizedText;
    import com.clubpenguin.lib.enums.Language; com.clubpenguin.lib.enums.Language;
    import com.clubpenguin.lib.vo.GameStringsVO; com.clubpenguin.lib.vo.GameStringsVO;
    import com.clubpenguin.tools.localtext.core.ILocalTextField; com.clubpenguin.tools.localtext.core.ILocalTextField;
    import com.clubpenguin.tools.localtext.component.ILocalTextComponent; com.clubpenguin.tools.localtext.component.ILocalTextComponent;
    import com.clubpenguin.lib.enums.resource.ResourceTypeEnum; com.clubpenguin.lib.enums.resource.ResourceTypeEnum;
    import com.clubpenguin.lib.vo.resource.ResourceVO; com.clubpenguin.lib.vo.resource.ResourceVO;
    import com.clubpenguin.lib.enums.resource.FurnitureTypeEnum; com.clubpenguin.lib.enums.resource.FurnitureTypeEnum;
    import com.clubpenguin.lib.vo.resource.FurnitureVO; com.clubpenguin.lib.vo.resource.FurnitureVO;
    import com.clubpenguin.lib.enums.resource.ClothingTypeEnum; com.clubpenguin.lib.enums.resource.ClothingTypeEnum;
    import com.clubpenguin.lib.enums.resource.FurnitureSortTypeEnum; com.clubpenguin.lib.enums.resource.FurnitureSortTypeEnum;
    import com.clubpenguin.lib.vo.resource.ClothingVO; com.clubpenguin.lib.vo.resource.ClothingVO;
    import com.clubpenguin.lib.vo.puffle.StatsVO; com.clubpenguin.lib.vo.puffle.StatsVO;
    import com.clubpenguin.lib.vo.puffle.MoodVO; com.clubpenguin.lib.vo.puffle.MoodVO;
    import com.clubpenguin.lib.services.notifications.INotificationService; com.clubpenguin.lib.services.notifications.INotificationService;
    import com.clubpenguin.lib.vo.quest.QuestVO; com.clubpenguin.lib.vo.quest.QuestVO;
    import com.clubpenguin.lib.util.StringUtils; com.clubpenguin.lib.util.StringUtils;
    import com.clubpenguin.lib.util.collection.Collection; com.clubpenguin.lib.util.collection.Collection;
    import com.clubpenguin.main.model.ActiveQuestsModel; com.clubpenguin.main.model.ActiveQuestsModel;
    import com.disney.disneylearning.managers.DLSManager; com.disney.disneylearning.managers.DLSManager;
    import com.clubpenguin.lib.enums.puffle.ConsumptionTypeEnum; com.clubpenguin.lib.enums.puffle.ConsumptionTypeEnum;
    import com.clubpenguin.lib.enums.puffle.PlayExternalEnum; com.clubpenguin.lib.enums.puffle.PlayExternalEnum;
    import com.clubpenguin.lib.services.socket.ConnectionConstants; com.clubpenguin.lib.services.socket.ConnectionConstants;
    import com.clubpenguin.services.socket.puffles.PuffleDataParser; com.clubpenguin.services.socket.puffles.PuffleDataParser;
    import com.clubpenguin.main.overlays.vo.MembershipFAQOverlayVO; com.clubpenguin.main.overlays.vo.MembershipFAQOverlayVO;
    import com.clubpenguin.main.overlays.vo.MembershipOverlayVO; com.clubpenguin.main.overlays.vo.MembershipOverlayVO;
    import com.playdom.tracker.OnlyTracker; com.playdom.tracker.OnlyTracker;
    import com.playdom.tracker.LogManager; com.playdom.tracker.LogManager;
    import com.playdom.util.NameValuesContainer; com.playdom.util.NameValuesContainer;
    import com.playdom.baseactors.BasePlayerStats; com.playdom.baseactors.BasePlayerStats;
    import com.playdom.tracker.PerformanceDelegate; com.playdom.tracker.PerformanceDelegate;
    import com.playdom.baseactors.BaseMoney; com.playdom.baseactors.BaseMoney;
    import com.clubpenguin.lib.enums.puffle.PuffleTypeEnum; com.clubpenguin.lib.enums.puffle.PuffleTypeEnum;
    import com.clubpenguin.lib.enums.puffle.PuffleSubTypeEnum; com.clubpenguin.lib.enums.puffle.PuffleSubTypeEnum;
    import com.clubpenguin.main.overlays.type.OverlayType; com.clubpenguin.main.overlays.type.OverlayType;
    import com.clubpenguin.lib.model.ICounters; com.clubpenguin.lib.model.ICounters;
    import com.adobe.serialization.json.JSONEncoder; com.adobe.serialization.json.JSONEncoder;
    import com.adobe.serialization.json.JSONDecoder; com.adobe.serialization.json.JSONDecoder;
    import com.clubpenguin.lib.friends.commands.AddInteractionCommand; com.clubpenguin.lib.friends.commands.AddInteractionCommand;
    import com.disney.friends.CredentialsVO; com.disney.friends.CredentialsVO;
    import com.clubpenguin.lib.friends.commands.RemoveMascotFriendCommand; com.clubpenguin.lib.friends.commands.RemoveMascotFriendCommand;
    import com.disney.friends.Friend; com.disney.friends.Friend;
    import com.clubpenguin.lib.friends.commands.AddIgnoredCommand; com.clubpenguin.lib.friends.commands.AddIgnoredCommand;
    import com.clubpenguin.lib.friends.commands.RequestFriendshipCommand; com.clubpenguin.lib.friends.commands.RequestFriendshipCommand;
    import com.clubpenguin.lib.friends.commands.PlayerFoundCommand; com.clubpenguin.lib.friends.commands.PlayerFoundCommand;
    import com.clubpenguin.lib.friends.commands.RemoveIgnoredCommand; com.clubpenguin.lib.friends.commands.RemoveIgnoredCommand;
    import com.clubpenguin.lib.friends.commands.ToggleFriendsUICommand; com.clubpenguin.lib.friends.commands.ToggleFriendsUICommand;
    import com.clubpenguin.lib.friends.commands.DisconnectFromFriendsCommand; com.clubpenguin.lib.friends.commands.DisconnectFromFriendsCommand;
    import com.clubpenguin.lib.friends.commands.HandleFriendsBridgeMsgCommand; com.clubpenguin.lib.friends.commands.HandleFriendsBridgeMsgCommand;
    import com.clubpenguin.lib.friends.commands.RemoveFriendshipCommand; com.clubpenguin.lib.friends.commands.RemoveFriendshipCommand;
    import com.clubpenguin.lib.friends.commands.HudVisibilityChangedCommand; com.clubpenguin.lib.friends.commands.HudVisibilityChangedCommand;
    import com.clubpenguin.lib.friends.commands.ConnectToFriendsCommand; com.clubpenguin.lib.friends.commands.ConnectToFriendsCommand;
    import com.clubpenguin.lib.friends.commands.jump.JumpToServerCommand; com.clubpenguin.lib.friends.commands.jump.JumpToServerCommand;
    import com.clubpenguin.lib.friends.commands.AddMascotFriendCommand; com.clubpenguin.lib.friends.commands.AddMascotFriendCommand;
    import com.clubpenguin.lib.friends.commands.jump.RequestReservationCommand; com.clubpenguin.lib.friends.commands.jump.RequestReservationCommand;
    import com.clubpenguin.lib.friends.commands.UpdatePresenceCommand; com.clubpenguin.lib.friends.commands.UpdatePresenceCommand;
    import com.disney.coupler.ICouplerGame; com.disney.coupler.ICouplerGame;
    import com.clubpenguin.game.ICPGame; com.clubpenguin.game.ICPGame;
    import com.clubpenguin.tools.localtext.core.TextBounds; com.clubpenguin.tools.localtext.core.TextBounds;
    import com.clubpenguin.lib.vo.puffle.LowStatVO; com.clubpenguin.lib.vo.puffle.LowStatVO;
    import com.clubpenguin.lib.services.notifications.IStampNotificationService; com.clubpenguin.lib.services.notifications.IStampNotificationService;
    import com.clubpenguin.lib.vo.quest.QuestStateEnum; com.clubpenguin.lib.vo.quest.QuestStateEnum;
    import com.clubpenguin.lib.vo.quest.QuestRewardEnum; com.clubpenguin.lib.vo.quest.QuestRewardEnum;
    import com.clubpenguin.lib.vo.quest.TaskVO; com.clubpenguin.lib.vo.quest.TaskVO;
    import com.clubpenguin.lib.vo.quest.VisitRoomTask; com.clubpenguin.lib.vo.quest.VisitRoomTask;
    import com.clubpenguin.lib.vo.quest.QuestRewardVO; com.clubpenguin.lib.vo.quest.QuestRewardVO;
    import com.disney.disneylearning.events.DLSEvent; com.disney.disneylearning.events.DLSEvent;
    import com.disney.disneylearning.managers.debug.DLSLocalConnectionProducer; com.disney.disneylearning.managers.debug.DLSLocalConnectionProducer;
    import com.adobe.crypto.MD5; com.adobe.crypto.MD5;
    import com.playdom.util.LogProxy; com.playdom.util.LogProxy;
    import com.clubpenguin.lib.services.http.HTTPServiceRequest; com.clubpenguin.lib.services.http.HTTPServiceRequest;
    import com.clubpenguin.lib.services.http.DirectoryListingWebService; com.clubpenguin.lib.services.http.DirectoryListingWebService;
    import com.clubpenguin.lib.event.FrameRateEvent; com.clubpenguin.lib.event.FrameRateEvent;
    import com.adobe.serialization.json.JSONTokenizer; com.adobe.serialization.json.JSONTokenizer;
    import com.adobe.serialization.json.JSONToken; com.adobe.serialization.json.JSONToken;
    import com.adobe.serialization.json.JSONTokenType; com.adobe.serialization.json.JSONTokenType;
    import com.disney.friends.FriendsService; com.disney.friends.FriendsService;
    import com.disney.friends.Presence; com.disney.friends.Presence;
    import it.gotoandplay.smartfoxserver.SmartFoxClient; it.gotoandplay.smartfoxserver.SmartFoxClient;
    import it.gotoandplay.smartfoxserver.SFSEvent; it.gotoandplay.smartfoxserver.SFSEvent;
    import com.disney.coupler.ICouplerHost; com.disney.coupler.ICouplerHost;
    import com.adobe.utils.IntUtil; com.adobe.utils.IntUtil;
    import com.clubpenguin.lib.services.http.HTTPResponse; com.clubpenguin.lib.services.http.HTTPResponse;
    import com.adobe.serialization.json.JSONParseError; com.adobe.serialization.json.JSONParseError;
    import com.disney.friends.FriendsEvent; com.disney.friends.FriendsEvent;
    import com.disney.friends.FriendsAPIConnection; com.disney.friends.FriendsAPIConnection;
    import com.disney.friends.Location; com.disney.friends.Location;
    import it.gotoandplay.smartfoxserver.data.Room; it.gotoandplay.smartfoxserver.data.Room;
    import it.gotoandplay.smartfoxserver.util.Entities; it.gotoandplay.smartfoxserver.util.Entities;
    import it.gotoandplay.smartfoxserver.util.ObjectSerializer; it.gotoandplay.smartfoxserver.util.ObjectSerializer;
    import it.gotoandplay.smartfoxserver.handlers.IMessageHandler; it.gotoandplay.smartfoxserver.handlers.IMessageHandler;
    import it.gotoandplay.smartfoxserver.handlers.ExtHandler; it.gotoandplay.smartfoxserver.handlers.ExtHandler;
    import it.gotoandplay.smartfoxserver.handlers.SysHandler; it.gotoandplay.smartfoxserver.handlers.SysHandler;
    import it.gotoandplay.smartfoxserver.data.User; it.gotoandplay.smartfoxserver.data.User;
