//Created by Action Script Viewer - https://www.buraks.com/asv
package com.clubpenguin.music
{
    import com.clubpenguin.lib.module.BaseModule;
    import com.clubpenguin.music.view.IMusicModuleContextView;
    import com.clubpenguin.lib.util.Log;
    import com.clubpenguin.music.context.MusicContext;

    public class MusicModule extends BaseModule implements IMusicModuleContextView 
    {

        public static const MUSIC_STUDIO_INSTANCE_NAME:String = "musicStudio";
        public static const SONG_LIST_INSTANCE_NAME:String = "songList";
        public static const MUSIC_WIDGET_INSTANCE_NAME:String = "musicWidget";

        public function MusicModule()
        {
            Log.debug("");
        }

        public function get isMusicStudioOpen():Boolean
        {
            return (!(getChildByName(MUSIC_STUDIO_INSTANCE_NAME) == null));
        }

        public function get isMusicWidgetOpen():Boolean
        {
            return (!(getChildByName(MUSIC_WIDGET_INSTANCE_NAME) == null));
        }

        public function get isMusicMySongListOpen():Boolean
        {
            return (!(getChildByName(SONG_LIST_INSTANCE_NAME) == null));
        }

        override public function init():void
        {
            Log.debug("");
            context = new MusicContext(this, injector);
        }


    }
}//package com.clubpenguin.music
    //force all classes
    import com.clubpenguin.music.view.IMusicModuleContextView; com.clubpenguin.music.view.IMusicModuleContextView;
    import com.clubpenguin.lib.module.BaseModule; com.clubpenguin.lib.module.BaseModule;
    import com.clubpenguin.music.MusicModule; com.clubpenguin.music.MusicModule;
    import org.robotlegs.core.IInjector; org.robotlegs.core.IInjector;
    import org.osflash.signals.IDispatcher; org.osflash.signals.IDispatcher;
    import org.osflash.signals.ISignal; org.osflash.signals.ISignal;
    import org.osflash.signals.Signal; org.osflash.signals.Signal;
    import com.clubpenguin.lib.module.IAppSignalBus; com.clubpenguin.lib.module.IAppSignalBus;
    import org.robotlegs.core.IContext; org.robotlegs.core.IContext;
    import org.robotlegs.base.ContextBase; org.robotlegs.base.ContextBase;
    import org.robotlegs.mvcs.Context; org.robotlegs.mvcs.Context;
    import org.robotlegs.core.ISignalContext; org.robotlegs.core.ISignalContext;
    import org.robotlegs.mvcs.SignalContext; org.robotlegs.mvcs.SignalContext;
    import com.clubpenguin.lib.module.BaseModuleContext; com.clubpenguin.lib.module.BaseModuleContext;
    import com.clubpenguin.music.context.MusicContext; com.clubpenguin.music.context.MusicContext;
    import com.clubpenguin.lib.util.Log; com.clubpenguin.lib.util.Log;
    import org.robotlegs.core.IEventMap; org.robotlegs.core.IEventMap;
    import org.robotlegs.base.EventMap; org.robotlegs.base.EventMap;
    import org.robotlegs.core.IReflector; org.robotlegs.core.IReflector;
    import org.robotlegs.core.ICommandMap; org.robotlegs.core.ICommandMap;
    import org.robotlegs.base.CommandMap; org.robotlegs.base.CommandMap;
    import org.robotlegs.core.IMediatorMap; org.robotlegs.core.IMediatorMap;
    import org.robotlegs.core.IViewMap; org.robotlegs.core.IViewMap;
    import org.robotlegs.base.ViewMapBase; org.robotlegs.base.ViewMapBase;
    import org.robotlegs.base.ViewMap; org.robotlegs.base.ViewMap;
    import org.robotlegs.base.ContextEvent; org.robotlegs.base.ContextEvent;
    import org.robotlegs.base.MediatorMap; org.robotlegs.base.MediatorMap;
    import org.swiftsuspenders.Injector; org.swiftsuspenders.Injector;
    import org.robotlegs.adapters.SwiftSuspendersInjector; org.robotlegs.adapters.SwiftSuspendersInjector;
    import org.swiftsuspenders.Reflector; org.swiftsuspenders.Reflector;
    import org.robotlegs.adapters.SwiftSuspendersReflector; org.robotlegs.adapters.SwiftSuspendersReflector;
    import org.robotlegs.core.ISignalCommandMap; org.robotlegs.core.ISignalCommandMap;
    import org.robotlegs.base.SignalCommandMap; org.robotlegs.base.SignalCommandMap;
    import org.robotlegs.mvcs.Command; org.robotlegs.mvcs.Command;
    import com.clubpenguin.lib.commands.CloseModuleCommand; com.clubpenguin.lib.commands.CloseModuleCommand;
    import com.clubpenguin.lib.signals.CloseModuleSignal; com.clubpenguin.lib.signals.CloseModuleSignal;
    import org.robotlegs.mvcs.SignalCommand; org.robotlegs.mvcs.SignalCommand;
    import com.clubpenguin.music.commands.HideMusicWidgetCommand; com.clubpenguin.music.commands.HideMusicWidgetCommand;
    import com.clubpenguin.music.commands.HideMusicStudioCommand; com.clubpenguin.music.commands.HideMusicStudioCommand;
    import org.robotlegs.mvcs.Actor; org.robotlegs.mvcs.Actor;
    import com.clubpenguin.lib.module.IAppModel; com.clubpenguin.lib.module.IAppModel;
    import com.clubpenguin.main.model.MainModel; com.clubpenguin.main.model.MainModel;
    import com.clubpenguin.music.TemporaryTriggers; com.clubpenguin.music.TemporaryTriggers;
    import com.clubpenguin.music.player.IMusicPlayer; com.clubpenguin.music.player.IMusicPlayer;
    import com.clubpenguin.music.player.MusicPlayer; com.clubpenguin.music.player.MusicPlayer;
    import com.clubpenguin.music.events.MusicModuleEvent; com.clubpenguin.music.events.MusicModuleEvent;
    import com.clubpenguin.music.commands.InitializeWidgetCommand; com.clubpenguin.music.commands.InitializeWidgetCommand;
    import com.clubpenguin.music.commands.InitializeMusicStudiobySignalCommand; com.clubpenguin.music.commands.InitializeMusicStudiobySignalCommand;
    import com.clubpenguin.music.commands.InitializeMusicStudioCommand; com.clubpenguin.music.commands.InitializeMusicStudioCommand;
    import com.clubpenguin.music.commands.UnmuteMusicPlayerCommand; com.clubpenguin.music.commands.UnmuteMusicPlayerCommand;
    import com.clubpenguin.music.commands.HideMusicModuleCommand; com.clubpenguin.music.commands.HideMusicModuleCommand;
    import org.robotlegs.core.IMediator; org.robotlegs.core.IMediator;
    import org.robotlegs.base.MediatorBase; org.robotlegs.base.MediatorBase;
    import org.robotlegs.mvcs.Mediator; org.robotlegs.mvcs.Mediator;
    import com.clubpenguin.music.TemporaryTriggersMediator; com.clubpenguin.music.TemporaryTriggersMediator;
    import com.clubpenguin.music.commands.MuteMusicPlayerCommand; com.clubpenguin.music.commands.MuteMusicPlayerCommand;
    import com.clubpenguin.main.signal.SignalBus; com.clubpenguin.main.signal.SignalBus;
    import com.clubpenguin.lib.services.socket.IConnection; com.clubpenguin.lib.services.socket.IConnection;
    import com.clubpenguin.music.commands.HideMySongListCommand; com.clubpenguin.music.commands.HideMySongListCommand;
    import com.clubpenguin.services.socket.music.IMusicService; com.clubpenguin.services.socket.music.IMusicService;
    import com.clubpenguin.services.socket.music.MusicService; com.clubpenguin.services.socket.music.MusicService;
    import com.clubpenguin.music.commands.InitializeMySongListCommand; com.clubpenguin.music.commands.InitializeMySongListCommand;
    import org.robotlegs.base.ContextError; org.robotlegs.base.ContextError;
    import org.swiftsuspenders.injectionpoints.InjectionPoint; org.swiftsuspenders.injectionpoints.InjectionPoint;
    import org.swiftsuspenders.injectionpoints.PropertyInjectionPoint; org.swiftsuspenders.injectionpoints.PropertyInjectionPoint;
    import org.swiftsuspenders.injectionpoints.NoParamsConstructorInjectionPoint; org.swiftsuspenders.injectionpoints.NoParamsConstructorInjectionPoint;
    import org.swiftsuspenders.injectionresults.InjectionResult; org.swiftsuspenders.injectionresults.InjectionResult;
    import org.swiftsuspenders.injectionresults.InjectClassResult; org.swiftsuspenders.injectionresults.InjectClassResult;
    import org.swiftsuspenders.injectionresults.InjectOtherRuleResult; org.swiftsuspenders.injectionresults.InjectOtherRuleResult;
    import org.swiftsuspenders.injectionresults.InjectSingletonResult; org.swiftsuspenders.injectionresults.InjectSingletonResult;
    import org.swiftsuspenders.injectionpoints.PostConstructInjectionPoint; org.swiftsuspenders.injectionpoints.PostConstructInjectionPoint;
// //     import org.swiftsuspenders.getConstructor; org.swiftsuspenders.getConstructor;
    import org.swiftsuspenders.InjectionConfig; org.swiftsuspenders.InjectionConfig;
    import org.swiftsuspenders.InjectorError; org.swiftsuspenders.InjectorError;
    import org.swiftsuspenders.injectionresults.InjectValueResult; org.swiftsuspenders.injectionresults.InjectValueResult;
    import org.swiftsuspenders.injectionpoints.MethodInjectionPoint; org.swiftsuspenders.injectionpoints.MethodInjectionPoint;
    import org.swiftsuspenders.injectionpoints.ConstructorInjectionPoint; org.swiftsuspenders.injectionpoints.ConstructorInjectionPoint;
    import com.clubpenguin.music.widget.MusicPlayerWidget; com.clubpenguin.music.widget.MusicPlayerWidget;
    import com.clubpenguin.music.game.MusicStudioModule; com.clubpenguin.music.game.MusicStudioModule;
    import com.clubpenguin.lib.vo.IPlayerVO; com.clubpenguin.lib.vo.IPlayerVO;
    import com.clubpenguin.lib.vo.PathsVO; com.clubpenguin.lib.vo.PathsVO;
    import com.clubpenguin.lib.services.IAVMBridgeService; com.clubpenguin.lib.services.IAVMBridgeService;
    import com.clubpenguin.lib.vo.EnvironmentDataVO; com.clubpenguin.lib.vo.EnvironmentDataVO;
    import com.clubpenguin.lib.managers.localization.ILocalizationManager; com.clubpenguin.lib.managers.localization.ILocalizationManager;
    import com.clubpenguin.managers.localization.LocalizationManager; com.clubpenguin.managers.localization.LocalizationManager;
    import com.clubpenguin.lib.view.BaseEmbeddedAssetView; com.clubpenguin.lib.view.BaseEmbeddedAssetView;
    import com.clubpenguin.main.view.PromptView; com.clubpenguin.main.view.PromptView;
    import com.clubpenguin.lib.managers.resource.IResourceManager; com.clubpenguin.lib.managers.resource.IResourceManager;
    import com.clubpenguin.managers.resource.ResourceManager; com.clubpenguin.managers.resource.ResourceManager;
    import com.clubpenguin.main.model.puffle.PuffleStateManager; com.clubpenguin.main.model.puffle.PuffleStateManager;
    import com.clubpenguin.lib.module.INotificationModule; com.clubpenguin.lib.module.INotificationModule;
    import com.clubpenguin.main.service.ErrorService; com.clubpenguin.main.service.ErrorService;
    import com.clubpenguin.lib.vo.AVMBridgeMessage; com.clubpenguin.lib.vo.AVMBridgeMessage;
    import com.clubpenguin.lib.enums.Enum; com.clubpenguin.lib.enums.Enum;
    import com.clubpenguin.lib.enums.errors.ErrorCodeEnum; com.clubpenguin.lib.enums.errors.ErrorCodeEnum;
    import com.clubpenguin.services.socket.world.WorldService; com.clubpenguin.services.socket.world.WorldService;
    import com.asual.swfaddress.SWFAddress; com.asual.swfaddress.SWFAddress;
    import com.asual.swfaddress.SWFAddressEvent; com.asual.swfaddress.SWFAddressEvent;
    import com.clubpenguin.lib.vo.PlayerVO; com.clubpenguin.lib.vo.PlayerVO;
    import com.clubpenguin.lib.module.WindowModuleContext; com.clubpenguin.lib.module.WindowModuleContext;
    import com.clubpenguin.main.view.MainView; com.clubpenguin.main.view.MainView;
    import com.clubpenguin.lib.services.AVMBridgeService; com.clubpenguin.lib.services.AVMBridgeService;
    import com.clubpenguin.main.service.DLearningService; com.clubpenguin.main.service.DLearningService;
    import com.clubpenguin.lib.vo.IVO; com.clubpenguin.lib.vo.IVO;
    import com.clubpenguin.lib.vo.puffle.CareItemVO; com.clubpenguin.lib.vo.puffle.CareItemVO;
    import com.hurlant.crypto.hash.IHash; com.hurlant.crypto.hash.IHash;
    import com.hurlant.crypto.hash.MD5; com.hurlant.crypto.hash.MD5;
    import com.clubpenguin.lib.util.collection.ICollection; com.clubpenguin.lib.util.collection.ICollection;
    import com.clubpenguin.lib.util.collection.Bag; com.clubpenguin.lib.util.collection.Bag;
    import com.clubpenguin.services.socket.puffles.PuffleService; com.clubpenguin.services.socket.puffles.PuffleService;
    import com.hurlant.util.Hex; com.hurlant.util.Hex;
    import com.clubpenguin.main.model.ModuleModel; com.clubpenguin.main.model.ModuleModel;
    import com.clubpenguin.lib.vo.ModuleVO; com.clubpenguin.lib.vo.ModuleVO;
    import com.clubpenguin.lib.module.ModuleFilenamesEnum; com.clubpenguin.lib.module.ModuleFilenamesEnum;
    import com.playdom.tracker.Tracker; com.playdom.tracker.Tracker;
    import com.clubpenguin.lib.vo.puffle.PuffleVO; com.clubpenguin.lib.vo.puffle.PuffleVO;
    import com.clubpenguin.managers.ILoadableAsset; com.clubpenguin.managers.ILoadableAsset;
    import com.clubpenguin.main.overlays.vo.OverlayVO; com.clubpenguin.main.overlays.vo.OverlayVO;
    import com.clubpenguin.main.overlays.vo.LoadingOverlayVO; com.clubpenguin.main.overlays.vo.LoadingOverlayVO;
    import com.clubpenguin.lib.vo.party.PartyVO; com.clubpenguin.lib.vo.party.PartyVO;
    import com.clubpenguin.lib.enums.puffle.CareItemInventoryTypeEnum; com.clubpenguin.lib.enums.puffle.CareItemInventoryTypeEnum;
    import com.clubpenguin.music.resources.song.SongRecorded; com.clubpenguin.music.resources.song.SongRecorded;
    import com.clubpenguin.music.widget.model.MusicWidgetModel; com.clubpenguin.music.widget.model.MusicWidgetModel;
    import com.clubpenguin.lib.vo.UserSubmissionVO; com.clubpenguin.lib.vo.UserSubmissionVO;
    import com.clubpenguin.main.overlays.vo.MembershipFAQOverlayVO; com.clubpenguin.main.overlays.vo.MembershipFAQOverlayVO;
    import com.clubpenguin.lib.vo.ErrorVO; com.clubpenguin.lib.vo.ErrorVO;
    import com.clubpenguin.main.overlays.vo.MembershipOverlayVO; com.clubpenguin.main.overlays.vo.MembershipOverlayVO;
    import com.clubpenguin.lib.vo.BiVO; com.clubpenguin.lib.vo.BiVO;
    import com.clubpenguin.music.mysonglist.MySongList; com.clubpenguin.music.mysonglist.MySongList;
    import com.clubpenguin.music.widget.events.MusicWidgetEvent; com.clubpenguin.music.widget.events.MusicWidgetEvent;
    import com.clubpenguin.services.socket.music.MusicDataEncoder; com.clubpenguin.services.socket.music.MusicDataEncoder;
    import com.clubpenguin.music.widget.MusicWidgetContext; com.clubpenguin.music.widget.MusicWidgetContext;
    import com.clubpenguin.music.game.context.MusicStudioContext; com.clubpenguin.music.game.context.MusicStudioContext;
    import com.clubpenguin.lib.enums.resource.CacheTypeEnum; com.clubpenguin.lib.enums.resource.CacheTypeEnum;
    import com.clubpenguin.tools.localtext.core.ILocalizedText; com.clubpenguin.tools.localtext.core.ILocalizedText;
    import com.clubpenguin.lib.enums.Language; com.clubpenguin.lib.enums.Language;
    import com.clubpenguin.lib.vo.GameStringsVO; com.clubpenguin.lib.vo.GameStringsVO;
    import com.clubpenguin.tools.localtext.core.ILocalTextField; com.clubpenguin.tools.localtext.core.ILocalTextField;
    import com.clubpenguin.tools.localtext.component.ILocalTextComponent; com.clubpenguin.tools.localtext.component.ILocalTextComponent;
    import com.clubpenguin.lib.enums.resource.ResourceTypeEnum; com.clubpenguin.lib.enums.resource.ResourceTypeEnum;
    import com.clubpenguin.lib.vo.resource.ResourceVO; com.clubpenguin.lib.vo.resource.ResourceVO;
    import com.clubpenguin.lib.enums.resource.FurnitureTypeEnum; com.clubpenguin.lib.enums.resource.FurnitureTypeEnum;
    import com.clubpenguin.lib.vo.resource.FurnitureVO; com.clubpenguin.lib.vo.resource.FurnitureVO;
    import com.clubpenguin.lib.enums.resource.ClothingTypeEnum; com.clubpenguin.lib.enums.resource.ClothingTypeEnum;
    import com.clubpenguin.lib.enums.resource.FurnitureSortTypeEnum; com.clubpenguin.lib.enums.resource.FurnitureSortTypeEnum;
    import com.clubpenguin.lib.vo.resource.ClothingVO; com.clubpenguin.lib.vo.resource.ClothingVO;
    import com.clubpenguin.lib.vo.puffle.StatsVO; com.clubpenguin.lib.vo.puffle.StatsVO;
    import com.clubpenguin.lib.vo.puffle.MoodVO; com.clubpenguin.lib.vo.puffle.MoodVO;
    import com.clubpenguin.lib.services.notifications.INotificationService; com.clubpenguin.lib.services.notifications.INotificationService;
    import com.clubpenguin.lib.vo.quest.QuestVO; com.clubpenguin.lib.vo.quest.QuestVO;
    import com.clubpenguin.lib.util.StringUtils; com.clubpenguin.lib.util.StringUtils;
    import com.clubpenguin.lib.util.collection.Collection; com.clubpenguin.lib.util.collection.Collection;
    import com.clubpenguin.main.model.ActiveQuestsModel; com.clubpenguin.main.model.ActiveQuestsModel;
    import com.clubpenguin.main.signal.loadingScreen.ShowLoadingScreenSignal; com.clubpenguin.main.signal.loadingScreen.ShowLoadingScreenSignal;
    import com.clubpenguin.lib.services.bi.RawBiService; com.clubpenguin.lib.services.bi.RawBiService;
    import com.clubpenguin.main.vo.ComplexPromptVO; com.clubpenguin.main.vo.ComplexPromptVO;
    import com.clubpenguin.main.signal.loadingScreen.UpdateLoadingScreenSignal; com.clubpenguin.main.signal.loadingScreen.UpdateLoadingScreenSignal;
    import com.gskinner.utils.SWFBridgeAS3; com.gskinner.utils.SWFBridgeAS3;
    import com.clubpenguin.main.signal.loadingScreen.HideLoadingScreenSignal; com.clubpenguin.main.signal.loadingScreen.HideLoadingScreenSignal;
    import com.clubpenguin.lib.services.LocalConnectionResponse; com.clubpenguin.lib.services.LocalConnectionResponse;
    import com.clubpenguin.lib.enums.metrics.MetricsConstant; com.clubpenguin.lib.enums.metrics.MetricsConstant;
    import com.clubpenguin.lib.model.IMetricsModel; com.clubpenguin.lib.model.IMetricsModel;
    import com.clubpenguin.main.vo.PromptVO; com.clubpenguin.main.vo.PromptVO;
    import com.clubpenguin.lib.vo.puffle.PuffleTreasureVO; com.clubpenguin.lib.vo.puffle.PuffleTreasureVO;
    import com.adobe.serialization.json.JSON; com.adobe.serialization.json.JSON;
    import com.clubpenguin.lib.vo.map.MapActionVO; com.clubpenguin.lib.vo.map.MapActionVO;
    import com.clubpenguin.lib.services.AVMBridgeMessageQueue; com.clubpenguin.lib.services.AVMBridgeMessageQueue;
    import com.clubpenguin.main.signal.QuestSettingsSignal; com.clubpenguin.main.signal.QuestSettingsSignal;
    import com.clubpenguin.lib.vo.BuddyVO; com.clubpenguin.lib.vo.BuddyVO;
    import com.clubpenguin.lib.friends.FriendsSignalBus; com.clubpenguin.lib.friends.FriendsSignalBus;
    import com.clubpenguin.main.signal.QuestStatusUpdatedSignal; com.clubpenguin.main.signal.QuestStatusUpdatedSignal;
    import com.clubpenguin.main.vo.AssetPromptVO; com.clubpenguin.main.vo.AssetPromptVO;
    import com.clubpenguin.lib.util.SecurityUtil; com.clubpenguin.lib.util.SecurityUtil;
    import com.disney.disneylearning.managers.DLSManager; com.disney.disneylearning.managers.DLSManager;
    import com.clubpenguin.lib.enums.puffle.ConsumptionTypeEnum; com.clubpenguin.lib.enums.puffle.ConsumptionTypeEnum;
    import com.clubpenguin.lib.enums.puffle.PlayExternalEnum; com.clubpenguin.lib.enums.puffle.PlayExternalEnum;
    import com.clubpenguin.lib.services.socket.ConnectionConstants; com.clubpenguin.lib.services.socket.ConnectionConstants;
    import com.clubpenguin.services.socket.puffles.PuffleDataParser; com.clubpenguin.services.socket.puffles.PuffleDataParser;
    import com.playdom.tracker.OnlyTracker; com.playdom.tracker.OnlyTracker;
    import com.playdom.tracker.LogManager; com.playdom.tracker.LogManager;
    import com.playdom.util.NameValuesContainer; com.playdom.util.NameValuesContainer;
    import com.playdom.baseactors.BasePlayerStats; com.playdom.baseactors.BasePlayerStats;
    import com.playdom.tracker.PerformanceDelegate; com.playdom.tracker.PerformanceDelegate;
    import com.playdom.baseactors.BaseMoney; com.playdom.baseactors.BaseMoney;
    import com.clubpenguin.lib.enums.puffle.PuffleTypeEnum; com.clubpenguin.lib.enums.puffle.PuffleTypeEnum;
    import com.clubpenguin.lib.enums.puffle.PuffleSubTypeEnum; com.clubpenguin.lib.enums.puffle.PuffleSubTypeEnum;
    import com.clubpenguin.main.overlays.type.OverlayType; com.clubpenguin.main.overlays.type.OverlayType;
    import com.clubpenguin.music.resources.song.RecordData; com.clubpenguin.music.resources.song.RecordData;
    import com.clubpenguin.music.widget.model.SharedTrackDataVO; com.clubpenguin.music.widget.model.SharedTrackDataVO;
    import com.clubpenguin.music.mysonglist.context.MySongListContext; com.clubpenguin.music.mysonglist.context.MySongListContext;
    import com.adobe.crypto.MD5; com.adobe.crypto.MD5;
    import com.clubpenguin.music.widget.controller.GetPlayerIgnoreListCommand; com.clubpenguin.music.widget.controller.GetPlayerIgnoreListCommand;
    import com.clubpenguin.music.widget.controller.GetBroadcastMusicTracksCommand; com.clubpenguin.music.widget.controller.GetBroadcastMusicTracksCommand;
    import com.clubpenguin.music.commands.MusicWidgetOnOverlayCountSubtract; com.clubpenguin.music.commands.MusicWidgetOnOverlayCountSubtract;
    import com.clubpenguin.music.commands.MusicWidgetOnOverlayCountAdd; com.clubpenguin.music.commands.MusicWidgetOnOverlayCountAdd;
    import com.clubpenguin.music.widget.controller.ShowSongListCommand; com.clubpenguin.music.widget.controller.ShowSongListCommand;
    import com.clubpenguin.music.widget.view.mediator.MainWidgetViewMediator; com.clubpenguin.music.widget.view.mediator.MainWidgetViewMediator;
    import com.clubpenguin.music.widget.view.component.MainWidgetView; com.clubpenguin.music.widget.view.component.MainWidgetView;
    import com.clubpenguin.music.widget.controller.LikeSongCommand; com.clubpenguin.music.widget.controller.LikeSongCommand;
    import com.clubpenguin.music.widget.controller.LoadMusicWidgetCommand; com.clubpenguin.music.widget.controller.LoadMusicWidgetCommand;
    import com.clubpenguin.music.widget.controller.HandleBroadcastMusicTracksCommand; com.clubpenguin.music.widget.controller.HandleBroadcastMusicTracksCommand;
    import com.clubpenguin.music.game.controller.PreviewStopSongCommand; com.clubpenguin.music.game.controller.PreviewStopSongCommand;
    import com.clubpenguin.music.game.controller.PlayGameCommand; com.clubpenguin.music.game.controller.PlayGameCommand;
    import com.clubpenguin.music.game.events.MusicStudioSongNameEvent; com.clubpenguin.music.game.events.MusicStudioSongNameEvent;
    import com.clubpenguin.music.game.controller.SetSongNameCommand; com.clubpenguin.music.game.controller.SetSongNameCommand;
    import com.clubpenguin.music.game.view.mediators.MusicStudioGameBoardMediator; com.clubpenguin.music.game.view.mediators.MusicStudioGameBoardMediator;
    import com.clubpenguin.music.game.controller.PlaySoundsCommand; com.clubpenguin.music.game.controller.PlaySoundsCommand;
    import com.clubpenguin.music.game.model.MusicStudioModel; com.clubpenguin.music.game.model.MusicStudioModel;
    import com.clubpenguin.music.game.view.interfaces.IMusicStudioStartSreen; com.clubpenguin.music.game.view.interfaces.IMusicStudioStartSreen;
    import com.clubpenguin.music.game.view.components.MusicStudioStartScreen; com.clubpenguin.music.game.view.components.MusicStudioStartScreen;
    import com.clubpenguin.music.game.controller.StopSongInMusicPlayerCommand; com.clubpenguin.music.game.controller.StopSongInMusicPlayerCommand;
    import com.clubpenguin.music.game.controller.ShowSavedTracksCommand; com.clubpenguin.music.game.controller.ShowSavedTracksCommand;
    import com.clubpenguin.music.game.view.mediators.MusicStudioPromptsMediator; com.clubpenguin.music.game.view.mediators.MusicStudioPromptsMediator;
    import com.clubpenguin.music.game.view.components.MusicStudio; com.clubpenguin.music.game.view.components.MusicStudio;
    import com.clubpenguin.music.game.controller.PreviewSongCommand; com.clubpenguin.music.game.controller.PreviewSongCommand;
    import com.clubpenguin.music.game.view.mediators.MusicStudioMediator; com.clubpenguin.music.game.view.mediators.MusicStudioMediator;
    import com.clubpenguin.music.game.view.interfaces.IMusicStudioInstructions; com.clubpenguin.music.game.view.interfaces.IMusicStudioInstructions;
    import com.clubpenguin.music.game.view.components.MusicStudioInstructions; com.clubpenguin.music.game.view.components.MusicStudioInstructions;
    import com.clubpenguin.music.game.service.INameValidationService; com.clubpenguin.music.game.service.INameValidationService;
    import com.clubpenguin.music.game.events.MusicStudioEvent; com.clubpenguin.music.game.events.MusicStudioEvent;
    import com.clubpenguin.music.game.controller.PlaySongInMusicPlayerCommand; com.clubpenguin.music.game.controller.PlaySongInMusicPlayerCommand;
    import com.clubpenguin.music.game.service.SongNameValidationService; com.clubpenguin.music.game.service.SongNameValidationService;
    import com.clubpenguin.music.game.controller.HideInstructionsCommand; com.clubpenguin.music.game.controller.HideInstructionsCommand;
    import com.clubpenguin.music.game.controller.SaveSongCommand; com.clubpenguin.music.game.controller.SaveSongCommand;
    import com.clubpenguin.music.game.events.MusicStudioSongEvent; com.clubpenguin.music.game.events.MusicStudioSongEvent;
    import com.clubpenguin.music.game.controller.ShowInstructionsCommand; com.clubpenguin.music.game.controller.ShowInstructionsCommand;
    import com.clubpenguin.music.game.controller.ExitGameCommand; com.clubpenguin.music.game.controller.ExitGameCommand;
    import com.clubpenguin.music.game.controller.ValidateSongNameCommand; com.clubpenguin.music.game.controller.ValidateSongNameCommand;
    import com.clubpenguin.music.game.controller.LikeSongCommand; com.clubpenguin.music.game.controller.LikeSongCommand;
    import com.clubpenguin.music.game.controller.InitializeServicesCommand; com.clubpenguin.music.game.controller.InitializeServicesCommand;
    import com.clubpenguin.music.game.controller.LoadMusicStudioCommand; com.clubpenguin.music.game.controller.LoadMusicStudioCommand;
    import com.clubpenguin.music.game.view.interfaces.IMusicStudioSongList; com.clubpenguin.music.game.view.interfaces.IMusicStudioSongList;
    import com.clubpenguin.music.game.view.components.base.UIView; com.clubpenguin.music.game.view.components.base.UIView;
    import com.clubpenguin.music.game.view.components.songList.MusicStudioSongList; com.clubpenguin.music.game.view.components.songList.MusicStudioSongList;
    import com.clubpenguin.music.game.controller.LoadGenreCommand; com.clubpenguin.music.game.controller.LoadGenreCommand;
    import com.clubpenguin.music.game.controller.StopRecordingCommand; com.clubpenguin.music.game.controller.StopRecordingCommand;
    import com.clubpenguin.music.game.controller.ShowStartScreenCommand; com.clubpenguin.music.game.controller.ShowStartScreenCommand;
    import com.clubpenguin.music.game.controller.CheckForEmptySaveSlotCommand; com.clubpenguin.music.game.controller.CheckForEmptySaveSlotCommand;
    import com.clubpenguin.music.game.controller.RecordMusicPulseCommand; com.clubpenguin.music.game.controller.RecordMusicPulseCommand;
    import com.clubpenguin.music.game.view.mediators.MusicStudioInstructionsMediator; com.clubpenguin.music.game.view.mediators.MusicStudioInstructionsMediator;
    import com.clubpenguin.music.game.view.interfaces.IMusicStudioPrompts; com.clubpenguin.music.game.view.interfaces.IMusicStudioPrompts;
    import com.clubpenguin.music.game.view.components.MusicStudioPrompts; com.clubpenguin.music.game.view.components.MusicStudioPrompts;
    import com.clubpenguin.music.game.controller.StartRecordingCommand; com.clubpenguin.music.game.controller.StartRecordingCommand;
    import com.clubpenguin.music.game.view.interfaces.IMusicStudioGameBoard; com.clubpenguin.music.game.view.interfaces.IMusicStudioGameBoard;
    import com.clubpenguin.music.game.view.components.MusicStudioGameBoard; com.clubpenguin.music.game.view.components.MusicStudioGameBoard;
    import com.clubpenguin.music.commands.JoinPreviousRoomCommand; com.clubpenguin.music.commands.JoinPreviousRoomCommand;
    import com.clubpenguin.music.game.view.mediators.MusicStudioStartScreenMediator; com.clubpenguin.music.game.view.mediators.MusicStudioStartScreenMediator;
    import com.clubpenguin.music.game.controller.GetSharedSongsCommand; com.clubpenguin.music.game.controller.GetSharedSongsCommand;
    import com.clubpenguin.music.game.view.mediators.songList.MusicStudioSongListMediator; com.clubpenguin.music.game.view.mediators.songList.MusicStudioSongListMediator;
    import com.clubpenguin.tools.localtext.core.TextBounds; com.clubpenguin.tools.localtext.core.TextBounds;
    import com.clubpenguin.lib.vo.puffle.LowStatVO; com.clubpenguin.lib.vo.puffle.LowStatVO;
    import com.clubpenguin.lib.services.notifications.IStampNotificationService; com.clubpenguin.lib.services.notifications.IStampNotificationService;
    import com.clubpenguin.lib.vo.quest.QuestStateEnum; com.clubpenguin.lib.vo.quest.QuestStateEnum;
    import com.clubpenguin.lib.vo.quest.QuestRewardEnum; com.clubpenguin.lib.vo.quest.QuestRewardEnum;
    import com.clubpenguin.lib.vo.quest.TaskVO; com.clubpenguin.lib.vo.quest.TaskVO;
    import com.clubpenguin.lib.vo.quest.VisitRoomTask; com.clubpenguin.lib.vo.quest.VisitRoomTask;
    import com.clubpenguin.lib.vo.quest.QuestRewardVO; com.clubpenguin.lib.vo.quest.QuestRewardVO;
    import com.clubpenguin.lib.model.ICounters; com.clubpenguin.lib.model.ICounters;
    import com.adobe.serialization.json.JSONEncoder; com.adobe.serialization.json.JSONEncoder;
    import com.adobe.serialization.json.JSONDecoder; com.adobe.serialization.json.JSONDecoder;
    import com.clubpenguin.lib.friends.commands.AddInteractionCommand; com.clubpenguin.lib.friends.commands.AddInteractionCommand;
    import com.disney.friends.CredentialsVO; com.disney.friends.CredentialsVO;
    import com.clubpenguin.lib.friends.commands.RemoveMascotFriendCommand; com.clubpenguin.lib.friends.commands.RemoveMascotFriendCommand;
    import com.disney.friends.Friend; com.disney.friends.Friend;
    import com.clubpenguin.lib.friends.commands.RequestFriendshipCommand; com.clubpenguin.lib.friends.commands.RequestFriendshipCommand;
    import com.clubpenguin.lib.friends.commands.AddIgnoredCommand; com.clubpenguin.lib.friends.commands.AddIgnoredCommand;
    import com.clubpenguin.lib.friends.commands.PlayerFoundCommand; com.clubpenguin.lib.friends.commands.PlayerFoundCommand;
    import com.clubpenguin.lib.friends.commands.RemoveIgnoredCommand; com.clubpenguin.lib.friends.commands.RemoveIgnoredCommand;
    import com.clubpenguin.lib.friends.commands.ToggleFriendsUICommand; com.clubpenguin.lib.friends.commands.ToggleFriendsUICommand;
    import com.clubpenguin.lib.friends.commands.DisconnectFromFriendsCommand; com.clubpenguin.lib.friends.commands.DisconnectFromFriendsCommand;
    import com.clubpenguin.lib.friends.commands.HandleFriendsBridgeMsgCommand; com.clubpenguin.lib.friends.commands.HandleFriendsBridgeMsgCommand;
    import com.clubpenguin.lib.friends.commands.RemoveFriendshipCommand; com.clubpenguin.lib.friends.commands.RemoveFriendshipCommand;
    import com.clubpenguin.lib.friends.commands.HudVisibilityChangedCommand; com.clubpenguin.lib.friends.commands.HudVisibilityChangedCommand;
    import com.clubpenguin.lib.friends.commands.ConnectToFriendsCommand; com.clubpenguin.lib.friends.commands.ConnectToFriendsCommand;
    import com.clubpenguin.lib.friends.commands.jump.JumpToServerCommand; com.clubpenguin.lib.friends.commands.jump.JumpToServerCommand;
    import com.clubpenguin.lib.friends.commands.AddMascotFriendCommand; com.clubpenguin.lib.friends.commands.AddMascotFriendCommand;
    import com.clubpenguin.lib.friends.commands.jump.RequestReservationCommand; com.clubpenguin.lib.friends.commands.jump.RequestReservationCommand;
    import com.clubpenguin.lib.friends.commands.UpdatePresenceCommand; com.clubpenguin.lib.friends.commands.UpdatePresenceCommand;
    import com.disney.disneylearning.events.DLSEvent; com.disney.disneylearning.events.DLSEvent;
    import com.disney.disneylearning.managers.debug.DLSLocalConnectionProducer; com.disney.disneylearning.managers.debug.DLSLocalConnectionProducer;
    import com.playdom.util.LogProxy; com.playdom.util.LogProxy;
    import com.clubpenguin.lib.event.FrameRateEvent; com.clubpenguin.lib.event.FrameRateEvent;
    import com.clubpenguin.music.mysonglist.controller.ShareSongCommand; com.clubpenguin.music.mysonglist.controller.ShareSongCommand;
    import com.clubpenguin.music.mysonglist.view.component.SongListView; com.clubpenguin.music.mysonglist.view.component.SongListView;
    import com.clubpenguin.music.mysonglist.controller.LoadMySongListCommand; com.clubpenguin.music.mysonglist.controller.LoadMySongListCommand;
    import com.clubpenguin.music.mysonglist.model.MySongListModel; com.clubpenguin.music.mysonglist.model.MySongListModel;
    import com.clubpenguin.music.mysonglist.controller.DeleteSongCommand; com.clubpenguin.music.mysonglist.controller.DeleteSongCommand;
    import com.clubpenguin.music.mysonglist.controller.PlaySongCommand; com.clubpenguin.music.mysonglist.controller.PlaySongCommand;
    import com.clubpenguin.music.mysonglist.controller.GetSongLikesCommand; com.clubpenguin.music.mysonglist.controller.GetSongLikesCommand;
    import com.clubpenguin.music.mysonglist.controller.OpenStudioCommand; com.clubpenguin.music.mysonglist.controller.OpenStudioCommand;
    import com.clubpenguin.music.mysonglist.view.mediator.SongListViewMediator; com.clubpenguin.music.mysonglist.view.mediator.SongListViewMediator;
    import com.clubpenguin.music.mysonglist.controller.CreateNewTrackCommand; com.clubpenguin.music.mysonglist.controller.CreateNewTrackCommand;
    import com.clubpenguin.music.mysonglist.controller.PauseSongCommand; com.clubpenguin.music.mysonglist.controller.PauseSongCommand;
    import com.clubpenguin.music.mysonglist.controller.CloseModuleCommand; com.clubpenguin.music.mysonglist.controller.CloseModuleCommand;
    import com.adobe.utils.IntUtil; com.adobe.utils.IntUtil;
    import com.clubpenguin.services.socket.music.IMusicLikesService; com.clubpenguin.services.socket.music.IMusicLikesService;
    import com.clubpenguin.music.view.components.likes.LikesButton; com.clubpenguin.music.view.components.likes.LikesButton;
    import com.clubpenguin.music.widget.controller.CheckCanLikeSongCommand; com.clubpenguin.music.widget.controller.CheckCanLikeSongCommand;
    import com.clubpenguin.music.game.events.MusicStudioViewEvent; com.clubpenguin.music.game.events.MusicStudioViewEvent;
    import com.clubpenguin.music.game.model.vo.SongNameValidationVO; com.clubpenguin.music.game.model.vo.SongNameValidationVO;
    import com.clubpenguin.music.game.model.enums.MusicStudioRecordingStatusEnum; com.clubpenguin.music.game.model.enums.MusicStudioRecordingStatusEnum;
    import com.clubpenguin.music.game.view.events.MusicStudioGameBoardEvent; com.clubpenguin.music.game.view.events.MusicStudioGameBoardEvent;
    import com.clubpenguin.music.game.model.cache.SongNameCache; com.clubpenguin.music.game.model.cache.SongNameCache;
    import com.clubpenguin.music.game.model.vo.SongDetailsVO; com.clubpenguin.music.game.model.vo.SongDetailsVO;
    import com.clubpenguin.music.game.view.events.MusicStudioStartScreenEvent; com.clubpenguin.music.game.view.events.MusicStudioStartScreenEvent;
    import com.clubpenguin.music.game.view.events.MusicStudioPromptEvent; com.clubpenguin.music.game.view.events.MusicStudioPromptEvent;
    import com.clubpenguin.music.game.view.events.MusicStudioInstructionsEvent; com.clubpenguin.music.game.view.events.MusicStudioInstructionsEvent;
    import com.clubpenguin.music.resources.scrollbar.ScrollControl_Studio; com.clubpenguin.music.resources.scrollbar.ScrollControl_Studio;
    import com.clubpenguin.music.game.view.components.songList.itemRenderer.SongListItem; com.clubpenguin.music.game.view.components.songList.itemRenderer.SongListItem;
    import com.clubpenguin.music.game.view.events.MusicStudioSongListEvent; com.clubpenguin.music.game.view.events.MusicStudioSongListEvent;
    import com.clubpenguin.music.game.view.events.MusicStudioSongListItemEvent; com.clubpenguin.music.game.view.events.MusicStudioSongListItemEvent;
    import com.clubpenguin.music.game.view.components.prompts.SaveSongPrompt; com.clubpenguin.music.game.view.components.prompts.SaveSongPrompt;
    import com.clubpenguin.music.game.view.components.grid.MusicStudioGameBoardGrid; com.clubpenguin.music.game.view.components.grid.MusicStudioGameBoardGrid;
    import com.clubpenguin.music.game.view.components.genres.MusicStudioGenreSelector; com.clubpenguin.music.game.view.components.genres.MusicStudioGenreSelector;
    import com.clubpenguin.music.game.view.components.recorder.MusicStudioRecorderBar; com.clubpenguin.music.game.view.components.recorder.MusicStudioRecorderBar;
    import com.adobe.serialization.json.JSONTokenizer; com.adobe.serialization.json.JSONTokenizer;
    import com.adobe.serialization.json.JSONToken; com.adobe.serialization.json.JSONToken;
    import com.adobe.serialization.json.JSONTokenType; com.adobe.serialization.json.JSONTokenType;
    import com.disney.friends.FriendsService; com.disney.friends.FriendsService;
    import com.disney.friends.Presence; com.disney.friends.Presence;
    import it.gotoandplay.smartfoxserver.SmartFoxClient; it.gotoandplay.smartfoxserver.SmartFoxClient;
    import it.gotoandplay.smartfoxserver.SFSEvent; it.gotoandplay.smartfoxserver.SFSEvent;
    import com.clubpenguin.music.mysonglist.model.SongDataVO; com.clubpenguin.music.mysonglist.model.SongDataVO;
    import com.clubpenguin.music.mysonglist.view.component.SharedTrackView; com.clubpenguin.music.mysonglist.view.component.SharedTrackView;
    import com.clubpenguin.music.mysonglist.view.component.SongView; com.clubpenguin.music.mysonglist.view.component.SongView;
    import com.clubpenguin.music.mysonglist.events.MySongListEvent; com.clubpenguin.music.mysonglist.events.MySongListEvent;
    import com.clubpenguin.music.mysonglist.controller.GetSongDataCommand; com.clubpenguin.music.mysonglist.controller.GetSongDataCommand;
    import com.clubpenguin.music.view.components.likes.NotificationBubble; com.clubpenguin.music.view.components.likes.NotificationBubble;
    import com.clubpenguin.music.game.view.components.grid.ToggleButton; com.clubpenguin.music.game.view.components.grid.ToggleButton;
    import com.adobe.serialization.json.JSONParseError; com.adobe.serialization.json.JSONParseError;
    import com.disney.friends.FriendsEvent; com.disney.friends.FriendsEvent;
    import com.disney.friends.FriendsAPIConnection; com.disney.friends.FriendsAPIConnection;
    import com.disney.friends.Location; com.disney.friends.Location;
    import it.gotoandplay.smartfoxserver.data.Room; it.gotoandplay.smartfoxserver.data.Room;
    import it.gotoandplay.smartfoxserver.util.Entities; it.gotoandplay.smartfoxserver.util.Entities;
    import it.gotoandplay.smartfoxserver.util.ObjectSerializer; it.gotoandplay.smartfoxserver.util.ObjectSerializer;
    import it.gotoandplay.smartfoxserver.handlers.IMessageHandler; it.gotoandplay.smartfoxserver.handlers.IMessageHandler;
    import it.gotoandplay.smartfoxserver.handlers.ExtHandler; it.gotoandplay.smartfoxserver.handlers.ExtHandler;
    import it.gotoandplay.smartfoxserver.handlers.SysHandler; it.gotoandplay.smartfoxserver.handlers.SysHandler;
    import it.gotoandplay.smartfoxserver.data.User; it.gotoandplay.smartfoxserver.data.User;
    import com.clubpenguin.music.resources.Utils; com.clubpenguin.music.resources.Utils;
