class com.clubpenguin.world.rooms2024.medieval.MedievalPartyConstants extends com.clubpenguin.party.template.TemplatedPartyConstants {
	static var PARTY_COOKIE_ID, TEMPLATED_COOKIE_HANDLER_NAME, TEMPLATED_RECEIVE_COMMAND_NAME, PARTY_SETTINGS_RESPONSE_NAME, MESSAGE_VIEWED_COMMAND, QC_MESSAGE_VIEWED_COMMAND, TASK_COMMAND, TRANSFORM_COLLECTION_KEY, QC_MESSAGE_KEY, MESSAGE_KEY, TASK_KEY, PARTY_DAY, TRANSFORM_REWARDS_KEY, IGLOO_FURNITURE_ITEMS, QUEST_UI_PATH, PARTY_CATALOGUE, IGLOO_LIST_PATH, IGLOO_PROMPT_PATH, PARTY_MAP, LOGIN_PROMPT_PATH, SCAVENGER_HUNT_PATH;
	function MedievalPartyConstants() {
		LOGIN_PROMPT_PATH = "w.p2024.medieval.login";
		PARTY_COOKIE_ID = "20240901";
	};
	static var LOGIN_WEEK2_PROMPT_PATH = "w.p2024.medieval.week2.login";
}